Fix in requirements.txt
With the missing = sign the command
pip install -r requirements.txt 
failed with the following message:

ValueError: ('Expected version spec in', 'tweepy=1.12', 'at', '=1.12')